name: backend CI/CD

on:
  push:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Set environment variables
      run: |
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_PATH=${{ secrets.DB_PATH }}" >> $GITHUB_ENV

    - name: Build and Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t ${{ secrets.DOCKER_USERNAME }}/flight-backend .
        docker push ${{ secrets.DOCKER_USERNAME }}/flight-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
  
    steps:
    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}  
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/flight-backend
          docker stop flight-backend || true
          docker rm flight-backend || true
          docker run -d --name flight-backend -p 80:80 ${{ secrets.DOCKER_USERNAME }}/flight-backend
